backend:
  name: git-gateway
  branch: main

media_folder: "public/stories"
public_folder: "stories"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "number", value_type: "int" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "poems"
    label: "Poems"
    folder: "src/content/poems"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "number", value_type: "int" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Poem Lines", name: "body", widget: "markdown" }

  - name: "stories"
    label: "Stories"
    folder: "src/content/stories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "number", value_type: "int" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "desc", widget: "string" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Image Alt Text", name: "alt", widget: "string" }
      - { label: "Intro Snippet", name: "intro", widget: "text" }
      - { label: "External Link (Medium)", name: "link", widget: "string" }